//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FareDeal.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_transactions
    {
        public System.Guid tran_id { get; set; }
        public System.Guid venue_id { get; set; }
        public System.Guid credit_id { get; set; }
        public System.DateTime purchase_time { get; set; }
        public bool payment_completed { get; set; }
        public string cc_type { get; set; }
        public string cc_number { get; set; }
        public string cc_exp_date { get; set; }
        public System.Guid user_id { get; set; }
        public string purchase_location_lat { get; set; }
        public string purchase_location_lng { get; set; }
    
        public virtual credit_master credit_master { get; set; }
        public virtual venue venue { get; set; }
    }
}
