//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FareDeal.Service.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FareDealDbContext : DbContext
    {
        public FareDealDbContext()
            : base("name=FareDealDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<credit_master> credit_master { get; set; }
        public virtual DbSet<credit_transactions> credit_transactions { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<venue> venues { get; set; }
        public virtual DbSet<deal> deals { get; set; }
        public virtual DbSet<deal_transcation> deal_transcation { get; set; }
        public virtual DbSet<venue_credit> venue_credit { get; set; }
    }
}
