//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FareDeal.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public location()
        {
            this.venues = new HashSet<venue>();
        }
    
        public System.Guid id { get; set; }
        public string lat { get; set; }
        public string lang { get; set; }
        public string postalcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string crossStreet { get; set; }
        public string cc { get; set; }
    
        public virtual ICollection<venue> venues { get; set; }
    }
}
