//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FareDeal.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        public venue()
        {
            this.credit_transactions = new HashSet<credit_transactions>();
            this.deals = new HashSet<deal>();
            this.venue_picture = new HashSet<venue_picture>();
        }
    
        public System.Guid Id { get; set; }
        public string name { get; set; }
        public string contact { get; set; }
        public bool chain { get; set; }
        public bool has_menu { get; set; }
        public string url { get; set; }
        public System.Guid category_id { get; set; }
        public System.Guid location_id { get; set; }
        public bool verified { get; set; }
        public short price_tier { get; set; }
        public string default_pic_url { get; set; }
        public bool is_open { get; set; }
        public string status { get; set; }
        public int credit_available { get; set; }
        public int credit_threshold { get; set; }
        public int credit_auto_increase { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<credit_transactions> credit_transactions { get; set; }
        public virtual ICollection<deal> deals { get; set; }
        public virtual location location { get; set; }
        public virtual ICollection<venue_picture> venue_picture { get; set; }
    }
}
