//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FareDeal.Service.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue_credit
    {
        public System.Guid Id { get; set; }
        public System.Guid venue_id { get; set; }
        public int credit_available { get; set; }
        public int credit_threhold { get; set; }
        public int credit_auto_increase { get; set; }
    
        public virtual venue venue { get; set; }
    }
}
