# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'authentication test' do

use_frameworks!
pod 'SwiftyJSON', '~> 2.2'

end

target 'authentication testTests' do

end

